### ISSUE TITLE
Ability to show On-Air with no jukebox or voting

### ISSUE THREAD

**Issue by jnpetersen** [whitesoup12/remote-falcon#112] opened 2023-11-29 00:02 UTC
**Is your feature request related to a problem? Please describe:**
There are times I'd like to have the page just show I'm on air to display what song is currently playing, but I don't want to allow people to control it.

**Describe the solution you'd like:**
For viewer page, have a drop down with multiple options (ie. Jukebox, Vote, Display Only)

**Comment by whitesoup12** [comment] 2023-12-01 02:52
Duplicate of #31

**Closed by whitesoup12** 2023-12-01 02:52 UTC
Labels: duplicate, enhancement
